/* Lógico_1: */

CREATE TABLE ESCOLA (
    cnpj INTEGER PRIMARY KEY UNIQUE,
    nome_escola CHARACTER NOT NULL,
    cidade CHARACTER NOT NULL,
    telefone VARCHAR NOT NULL,
    endereco VARCHAR NOT NULL
);

CREATE TABLE TURMA (
    codigo INTEGER PRIMARY KEY,
    nome VARCHAR NOT NULL,
    turno CHARACTER NOT NULL,
    id_disciplina INTEGER NOT NULL
);

CREATE TABLE PROFESSOR (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR NOT NULL,
    id_disciplina INTEGER NOT NULL,
    telefone VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE DISCIPLINA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR NOT NULL,
    id_professor INTEGER NOT NULL
);

CREATE TABLE ALUNO (
    cpf INTEGER PRIMARY KEY,
    nome VARCHAR NOT NULL,
    dt_nascimento DATE NOT NULL,
    idade INTEGER NOT NULL,
    cd_turma VARCHAR NOT NULL,
    id_resp INTEGER NOT NULL,
    FOREIGN KEY (cd_turma) REFERENCES TURMA (codigo),
    FOREIGN KEY (id_resp) REFERENCES RESPONSAVEL (id),
    
);

CREATE TABLE RESPONSAVEL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cpf INTEGER NOT NULL,
    rg INTEGER NOT NULL,
    nome VARCHAR NOT NULL,
    dt_nascimento DATE NOT NULL
);

 
ALTER TABLE TURMA ADD CONSTRAINT FK_TURMA_2
    FOREIGN KEY (id_disciplina)
    REFERENCES DISCIPLINA (id);
 
ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_2
    FOREIGN KEY (id_disciplina)
    REFERENCES DISCIPLINA (id);
 
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_2
    FOREIGN KEY (id_professor)
    REFERENCES PROFESSOR (id);